# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  displayName: "Download qscanner"
  inputs:
    scriptType: bash
    targetType: 'inline'
    script: |
        wget https://www.qualys.com/qscanner/download/v4.4.0/download_qscanner.sh
        chmod +x download_qscanner.sh
        ./download_qscanner.sh
        ls -la
        chmod +x linux-amd64/qscanner
- task: Bash@3
  displayName: "Run QScanner"
  inputs:
    targetType: 'inline'
    script: |
      # Execute the qscanner command
      cd linux-amd64
      ./qscanner image mtaru/ubuntu --mode get-report --pod US1 --access-token "token" --tags "cicdtest" --report-format sarif,table --output-dir "$(Build.SourcesDirectory)/qualys"
      mkdir -p $(Build.SourcesDirectory)/sarif_reports
      cp /home/vsts/work/1/s/qualys/* $(Build.SourcesDirectory)/sarif_reports
      chmod -R a+rwx $(Build.SourcesDirectory)/sarif_reports
- task: QualysCSConnector@4
  inputs:
    QualysApiServer: 'https://qualysapi.qualys.com'
    QualysApiUsername: 'user'
    QualysApiPassword: 'pwd'
    imageID: 'mtaru/ubuntu:latest'
    dockerUrl: 'unix:///var/run/docker.sock'
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.SourcesDirectory)/sarif_reports'
    artifactName: 'CodeAnalysisLogs'
  displayName: 'Publish SARIF Reports as Artifact'
